test:
  image: archlinux
  before_script:
    - pacman -Syu --noconfirm asciidoc autoconf fakeroot pacman perl
    - ./autogen.sh
    - ./configure
    - make
  script: make check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
